export const emotes = {
  streamerEmotes: {
    lfs0: 'https://s3-us-west-1.amazonaws.com/twitchchat/lfs0.jpg',
    lfs00: 'https://s3-us-west-1.amazonaws.com/twitchchat/lfs00.jpg',
    lfs11: 'https://s3-us-west-1.amazonaws.com/twitchchat/lfs11.jpg',
    lfs22: 'https://s3-us-west-1.amazonaws.com/twitchchat/lfs22.jpg',
    lfs3: 'https://s3-us-west-1.amazonaws.com/twitchchat/lfs3.jpg',
    lfs33: 'https://s3-us-west-1.amazonaws.com/twitchchat/lfs33.jpg',
    lfs4: 'https://s3-us-west-1.amazonaws.com/twitchchat/lfs4.jpg',
    lfs420: 'https://s3-us-west-1.amazonaws.com/twitchchat/lfs420.jpg',
    lfs44: 'https://s3-us-west-1.amazonaws.com/twitchchat/lfs44.jpg',
    lfs5: 'https://s3-us-west-1.amazonaws.com/twitchchat/lfs5.jpg',
    lfs66: 'https://s3-us-west-1.amazonaws.com/twitchchat/lfs66.jpg',
    lfs666: 'https://s3-us-west-1.amazonaws.com/twitchchat/lfs666.jpg',
    lfs69: 'https://s3-us-west-1.amazonaws.com/twitchchat/lfs69.jpg',
    lfs7: 'https://s3-us-west-1.amazonaws.com/twitchchat/lfs7.jpg',
    lfs8: 'https://s3-us-west-1.amazonaws.com/twitchchat/lfs8.jpg',
    lfs9: 'https://s3-us-west-1.amazonaws.com/twitchchat/lfs9.jpg',
    lfsA: 'https://s3-us-west-1.amazonaws.com/twitchchat/lfsA.jpg',
    lfsB: 'https://s3-us-west-1.amazonaws.com/twitchchat/lfsB.jpg',
    lfsC: 'https://s3-us-west-1.amazonaws.com/twitchchat/lfsC.jpg',
    lfsD: 'https://s3-us-west-1.amazonaws.com/twitchchat/lfsD.jpg',
    lfsE: 'https://s3-us-west-1.amazonaws.com/twitchchat/lfsE.jpg',
    lfsF: 'https://s3-us-west-1.amazonaws.com/twitchchat/lfsF.jpg',
    lfsFP: 'https://s3-us-west-1.amazonaws.com/twitchchat/lfsFP.jpg',
    lfsG: 'https://s3-us-west-1.amazonaws.com/twitchchat/lfsG.jpg',
    lfsH: 'https://s3-us-west-1.amazonaws.com/twitchchat/lfsH.jpg',
    lfsI: 'https://s3-us-west-1.amazonaws.com/twitchchat/lfsI.jpg',
    lfsJ: 'https://s3-us-west-1.amazonaws.com/twitchchat/lfsJ.jpg',
    lfsK: 'https://s3-us-west-1.amazonaws.com/twitchchat/lfsK.jpg',
    lfsL: 'https://s3-us-west-1.amazonaws.com/twitchchat/lfsL.jpg',
    lfsLB: 'https://s3-us-west-1.amazonaws.com/twitchchat/lfsLB.jpg',
    lfsM: 'https://s3-us-west-1.amazonaws.com/twitchchat/lfsM.jpg',
    lfsN: 'https://s3-us-west-1.amazonaws.com/twitchchat/lfsN.jpg',
    lfsO: 'https://s3-us-west-1.amazonaws.com/twitchchat/lfsO.jpg',
    lfsOMG: 'https://s3-us-west-1.amazonaws.com/twitchchat/lfsOMG.jpg',
    lfsP: 'https://s3-us-west-1.amazonaws.com/twitchchat/lfsP.jpg',
    lfsQ: 'https://s3-us-west-1.amazonaws.com/twitchchat/lfsQ.jpg',
    lfsR: 'https://s3-us-west-1.amazonaws.com/twitchchat/lfsR.jpg',
    lfsS: 'https://s3-us-west-1.amazonaws.com/twitchchat/lfsS.jpg',
    lfsT: 'https://s3-us-west-1.amazonaws.com/twitchchat/lfsT.jpg',
    lfsU: 'https://s3-us-west-1.amazonaws.com/twitchchat/lfsU.jpg',
    lfsV: 'https://s3-us-west-1.amazonaws.com/twitchchat/lfsV.jpg',
    lfsW: 'https://s3-us-west-1.amazonaws.com/twitchchat/lfsW.jpg',
    lfsWT: 'https://s3-us-west-1.amazonaws.com/twitchchat/lfsWT.jpg',
    lfsX: 'https://s3-us-west-1.amazonaws.com/twitchchat/lfsX.jpg',
    lfsY: 'https://s3-us-west-1.amazonaws.com/twitchchat/lfsY.jpg',
    lfsZ: 'https://s3-us-west-1.amazonaws.com/twitchchat/lfsZ.jpg'
  },
  globalEmotes: {
    '<3': 'https://s3-us-west-1.amazonaws.com/twitchchat/<3.png',
    '>(': 'https://s3-us-west-1.amazonaws.com/twitchchat/noo.png',
    ':D': 'https://s3-us-west-1.amazonaws.com/twitchchat/D.png',
    'o_O': 'https://s3-us-west-1.amazonaws.com/twitchchat/o_O.png',
    'R)': 'https://s3-us-west-1.amazonaws.com/twitchchat/eyepatch.png',
    ':p': 'https://s3-us-west-1.amazonaws.com/twitchchat/p.png',
    ';p': 'https://s3-us-west-1.amazonaws.com/twitchchat/winkyp.png',
    ';)': 'https://s3-us-west-1.amazonaws.com/twitchchat/wink.png',
    ':\\': 'https://s3-us-west-1.amazonaws.com/twitchchat/o.png',
    'B)': 'https://s3-us-west-1.amazonaws.com/twitchchat/cool.png',
    ':z': 'https://s3-us-west-1.amazonaws.com/twitchchat/z.png',
    ':o': 'https://s3-us-west-1.amazonaws.com/twitchchat/o.png',
    ':(': 'https://s3-us-west-1.amazonaws.com/twitchchat/sad.png',
    ':)': 'https://s3-us-west-1.amazonaws.com/twitchchat/smile.png',
    '4Head': 'https://s3-us-west-1.amazonaws.com/twitchchat/4Head.jpg',
    ANELE: 'https://s3-us-west-1.amazonaws.com/twitchchat/ANELE.jpg',
    AngryJack: 'https://s3-us-west-1.amazonaws.com/twitchchat/AngryJack.jpg',
    AquamanGG: 'https://s3-us-west-1.amazonaws.com/twitchchat/AquamanGG.jpg',
    ArgieB8: 'https://s3-us-west-1.amazonaws.com/twitchchat/ArgieB8.jpg',
    ArigatoNas: 'https://s3-us-west-1.amazonaws.com/twitchchat/ArigatoNas.jpg',
    ArsonNoSexy: 'https://s3-us-west-1.amazonaws.com/twitchchat/ArsonNoSexy.jpg',
    AsexualPride:
      'https://s3-us-west-1.amazonaws.com/twitchchat/AsexualPride.jpg',
    AsianGlow: 'https://s3-us-west-1.amazonaws.com/twitchchat/AsianGlow.jpg',
    BCWarrior: 'https://s3-us-west-1.amazonaws.com/twitchchat/BCWarrior.jpg',
    BabyRage: 'https://s3-us-west-1.amazonaws.com/twitchchat/BabyRage.jpg',
    BatChest: 'https://s3-us-west-1.amazonaws.com/twitchchat/BatChest.jpg',
    BegWan: 'https://s3-us-west-1.amazonaws.com/twitchchat/BegWan.jpg',
    BibleThump: 'https://s3-us-west-1.amazonaws.com/twitchchat/BibleThump.jpg',
    BigBrother: 'https://s3-us-west-1.amazonaws.com/twitchchat/BigBrother.jpg',
    BigPhish: 'https://s3-us-west-1.amazonaws.com/twitchchat/BigPhish.jpg',
    BisexualPride:
      'https://s3-us-west-1.amazonaws.com/twitchchat/BisexualPride.jpg',
    BlargNaut: 'https://s3-us-west-1.amazonaws.com/twitchchat/BlargNaut.jpg',
    BlessRNG: 'https://s3-us-west-1.amazonaws.com/twitchchat/BlessRNG.jpg',
    BloodTrail: 'https://s3-us-west-1.amazonaws.com/twitchchat/BloodTrail.jpg',
    BrainSlug: 'https://s3-us-west-1.amazonaws.com/twitchchat/BrainSlug.jpg',
    BrokeBack: 'https://s3-us-west-1.amazonaws.com/twitchchat/BrokeBack.jpg',
    BuddhaBar: 'https://s3-us-west-1.amazonaws.com/twitchchat/BuddhaBar.jpg',
    CarlSmile: 'https://s3-us-west-1.amazonaws.com/twitchchat/CarlSmile.jpg',
    ChefFrank: 'https://s3-us-west-1.amazonaws.com/twitchchat/ChefFrank.jpg',
    CoolCat: 'https://s3-us-west-1.amazonaws.com/twitchchat/CoolCat.jpg',
    CoolStoryBob:
      'https://s3-us-west-1.amazonaws.com/twitchchat/CoolStoryBob.jpg',
    CorgiDerp: 'https://s3-us-west-1.amazonaws.com/twitchchat/CorgiDerp.jpg',
    CrreamAwk: 'https://s3-us-west-1.amazonaws.com/twitchchat/CrreamAwk.jpg',
    CurseLit: 'https://s3-us-west-1.amazonaws.com/twitchchat/CurseLit.jpg',
    DAESuppy: 'https://s3-us-west-1.amazonaws.com/twitchchat/DAESuppy.jpg',
    DBstyle: 'https://s3-us-west-1.amazonaws.com/twitchchat/DBstyle.jpg',
    DansGame: 'https://s3-us-west-1.amazonaws.com/twitchchat/DansGame.jpg',
    DarkMode: 'https://s3-us-west-1.amazonaws.com/twitchchat/DarkMode.jpg',
    DatSheffy: 'https://s3-us-west-1.amazonaws.com/twitchchat/DatSheffy.jpg',
    DendiFace: 'https://s3-us-west-1.amazonaws.com/twitchchat/DendiFace.jpg',
    DogFace: 'https://s3-us-west-1.amazonaws.com/twitchchat/DogFace.jpg',
    DoritosChip: 'https://s3-us-west-1.amazonaws.com/twitchchat/DoritosChip.jpg',
    DrinkPurple: 'https://s3-us-west-1.amazonaws.com/twitchchat/DrinkPurple.jpg',
    DxCat: 'https://s3-us-west-1.amazonaws.com/twitchchat/DxCat.jpg',
    EarthDay: 'https://s3-us-west-1.amazonaws.com/twitchchat/EarthDay.jpg',
    EleGiggle: 'https://s3-us-west-1.amazonaws.com/twitchchat/EleGiggle.jpg',
    EntropyWins: 'https://s3-us-west-1.amazonaws.com/twitchchat/EntropyWins.jpg',
    FBBlock: 'https://s3-us-west-1.amazonaws.com/twitchchat/FBBlock.jpg',
    FBCatch: 'https://s3-us-west-1.amazonaws.com/twitchchat/FBCatch.jpg',
    FBChallenge: 'https://s3-us-west-1.amazonaws.com/twitchchat/FBChallenge.jpg',
    FBPass: 'https://s3-us-west-1.amazonaws.com/twitchchat/FBPass.jpg',
    FBPenalty: 'https://s3-us-west-1.amazonaws.com/twitchchat/FBPenalty.jpg',
    FBRun: 'https://s3-us-west-1.amazonaws.com/twitchchat/FBRun.jpg',
    FBSpiral: 'https://s3-us-west-1.amazonaws.com/twitchchat/FBSpiral.jpg',
    FBtouchdown: 'https://s3-us-west-1.amazonaws.com/twitchchat/FBtouchdown.jpg',
    FUNgineer: 'https://s3-us-west-1.amazonaws.com/twitchchat/FUNgineer.jpg',
    FailFish: 'https://s3-us-west-1.amazonaws.com/twitchchat/FailFish.jpg',
    FrankerZ: 'https://s3-us-west-1.amazonaws.com/twitchchat/FrankerZ.jpg',
    FreakinStinkin:
      'https://s3-us-west-1.amazonaws.com/twitchchat/FreakinStinkin.jpg',
    FutureMan: 'https://s3-us-west-1.amazonaws.com/twitchchat/FutureMan.jpg',
    GayPride: 'https://s3-us-west-1.amazonaws.com/twitchchat/GayPride.jpg',
    GenderFluidPride:
      'https://s3-us-west-1.amazonaws.com/twitchchat/GenderFluidPride.jpg',
    GingerPower: 'https://s3-us-west-1.amazonaws.com/twitchchat/GingerPower.jpg',
    GivePLZ: 'https://s3-us-west-1.amazonaws.com/twitchchat/GivePLZ.jpg',
    GrammarKing: 'https://s3-us-west-1.amazonaws.com/twitchchat/GrammarKing.jpg',
    GreenTeam: 'https://s3-us-west-1.amazonaws.com/twitchchat/GreenTeam.jpg',
    GunRun: 'https://s3-us-west-1.amazonaws.com/twitchchat/GunRun.jpg',
    HSCheers: 'https://s3-us-west-1.amazonaws.com/twitchchat/HSCheers.jpg',
    HSWP: 'https://s3-us-west-1.amazonaws.com/twitchchat/HSWP.jpg',
    HappyJack: 'https://s3-us-west-1.amazonaws.com/twitchchat/HappyJack.jpg',
    HassaanChop: 'https://s3-us-west-1.amazonaws.com/twitchchat/HassaanChop.jpg',
    HassanChop: 'https://s3-us-west-1.amazonaws.com/twitchchat/HassanChop.jpg',
    HeyGuys: 'https://s3-us-west-1.amazonaws.com/twitchchat/HeyGuys.jpg',
    HolidayCookie:
      'https://s3-us-west-1.amazonaws.com/twitchchat/HolidayCookie.jpg',
    HolidayLog: 'https://s3-us-west-1.amazonaws.com/twitchchat/HolidayLog.jpg',
    HolidayOrnament:
      'https://s3-us-west-1.amazonaws.com/twitchchat/HolidayOrnament.jpg',
    HolidayPresent:
      'https://s3-us-west-1.amazonaws.com/twitchchat/HolidayPresent.jpg',
    HolidaySanta:
      'https://s3-us-west-1.amazonaws.com/twitchchat/HolidaySanta.jpg',
    HotPokket: 'https://s3-us-west-1.amazonaws.com/twitchchat/HotPokket.jpg',
    HumbleLife: 'https://s3-us-west-1.amazonaws.com/twitchchat/HumbleLife.jpg',
    IntersexPride:
      'https://s3-us-west-1.amazonaws.com/twitchchat/IntersexPride.jpg',
    InuyoFace: 'https://s3-us-west-1.amazonaws.com/twitchchat/InuyoFace.jpg',
    ItsBoshyTime:
      'https://s3-us-west-1.amazonaws.com/twitchchat/ItsBoshyTime.jpg',
    JKanStyle: 'https://s3-us-west-1.amazonaws.com/twitchchat/JKanStyle.jpg',
    Jebaited: 'https://s3-us-west-1.amazonaws.com/twitchchat/Jebaited.jpg',
    JonCarnage: 'https://s3-us-west-1.amazonaws.com/twitchchat/JonCarnage.jpg',
    KAPOW: 'https://s3-us-west-1.amazonaws.com/twitchchat/KAPOW.jpg',
    Kappa: 'https://s3-us-west-1.amazonaws.com/twitchchat/Kappa.jpg',
    KappaClaus: 'https://s3-us-west-1.amazonaws.com/twitchchat/KappaClaus.jpg',
    KappaPride: 'https://s3-us-west-1.amazonaws.com/twitchchat/KappaPride.jpg',
    KappaRoss: 'https://s3-us-west-1.amazonaws.com/twitchchat/KappaRoss.jpg',
    KappaWealth: 'https://s3-us-west-1.amazonaws.com/twitchchat/KappaWealth.jpg',
    Kappu: 'https://s3-us-west-1.amazonaws.com/twitchchat/Kappu.jpg',
    Keepo: 'https://s3-us-west-1.amazonaws.com/twitchchat/Keepo.jpg',
    KevinTurtle: 'https://s3-us-west-1.amazonaws.com/twitchchat/KevinTurtle.jpg',
    Kippa: 'https://s3-us-west-1.amazonaws.com/twitchchat/Kippa.jpg',
    KomodoHype: 'https://s3-us-west-1.amazonaws.com/twitchchat/KomodoHype.jpg',
    KonCha: 'https://s3-us-west-1.amazonaws.com/twitchchat/KonCha.jpg',
    Kreygasm: 'https://s3-us-west-1.amazonaws.com/twitchchat/Kreygasm.jpg',
    LUL: 'https://s3-us-west-1.amazonaws.com/twitchchat/LUL.jpg',
    LesbianPride:
      'https://s3-us-west-1.amazonaws.com/twitchchat/LesbianPride.jpg',
    MVGame: 'https://s3-us-west-1.amazonaws.com/twitchchat/MVGame.jpg',
    Mau5: 'https://s3-us-west-1.amazonaws.com/twitchchat/Mau5.jpg',
    MaxLOL: 'https://s3-us-west-1.amazonaws.com/twitchchat/MaxLOL.jpg',
    MercyWing1: 'https://s3-us-west-1.amazonaws.com/twitchchat/MercyWing1.jpg',
    MercyWing2: 'https://s3-us-west-1.amazonaws.com/twitchchat/MercyWing2.jpg',
    MikeHogu: 'https://s3-us-west-1.amazonaws.com/twitchchat/MikeHogu.jpg',
    MingLee: 'https://s3-us-west-1.amazonaws.com/twitchchat/MingLee.jpg',
    MorphinTime: 'https://s3-us-west-1.amazonaws.com/twitchchat/MorphinTime.jpg',
    MrDestructoid:
      'https://s3-us-west-1.amazonaws.com/twitchchat/MrDestructoid.jpg',
    NinjaGrumpy: 'https://s3-us-west-1.amazonaws.com/twitchchat/NinjaGrumpy.jpg',
    NomNom: 'https://s3-us-west-1.amazonaws.com/twitchchat/NomNom.jpg',
    NonBinaryPride:
      'https://s3-us-west-1.amazonaws.com/twitchchat/NonBinaryPride.jpg',
    NotATK: 'https://s3-us-west-1.amazonaws.com/twitchchat/NotATK.jpg',
    NotLikeThis: 'https://s3-us-west-1.amazonaws.com/twitchchat/NotLikeThis.jpg',
    OSFrog: 'https://s3-us-west-1.amazonaws.com/twitchchat/OSFrog.jpg',
    OhMyDog: 'https://s3-us-west-1.amazonaws.com/twitchchat/OhMyDog.jpg',
    OneHand: 'https://s3-us-west-1.amazonaws.com/twitchchat/OneHand.jpg',
    OpieOP: 'https://s3-us-west-1.amazonaws.com/twitchchat/OpieOP.jpg',
    OptimizePrime:
      'https://s3-us-west-1.amazonaws.com/twitchchat/OptimizePrime.jpg',
    PJSalt: 'https://s3-us-west-1.amazonaws.com/twitchchat/PJSalt.jpg',
    PJSugar: 'https://s3-us-west-1.amazonaws.com/twitchchat/PJSugar.jpg',
    PMSTwin: 'https://s3-us-west-1.amazonaws.com/twitchchat/PMSTwin.jpg',
    PRChase: 'https://s3-us-west-1.amazonaws.com/twitchchat/PRChase.jpg',
    PanicVis: 'https://s3-us-west-1.amazonaws.com/twitchchat/PanicVis.jpg',
    PansexualPride:
      'https://s3-us-west-1.amazonaws.com/twitchchat/PansexualPride.jpg',
    PartyHat: 'https://s3-us-west-1.amazonaws.com/twitchchat/PartyHat.jpg',
    PartyTime: 'https://s3-us-west-1.amazonaws.com/twitchchat/PartyTime.jpg',
    PeoplesChamp:
      'https://s3-us-west-1.amazonaws.com/twitchchat/PeoplesChamp.jpg',
    PermaSmug: 'https://s3-us-west-1.amazonaws.com/twitchchat/PermaSmug.jpg',
    PeteZaroll: 'https://s3-us-west-1.amazonaws.com/twitchchat/PeteZaroll.jpg',
    PeteZarollOdyssey:
      'https://s3-us-west-1.amazonaws.com/twitchchat/PeteZarollOdyssey.jpg',
    PicoMause: 'https://s3-us-west-1.amazonaws.com/twitchchat/PicoMause.jpg',
    PinkMercy: 'https://s3-us-west-1.amazonaws.com/twitchchat/PinkMercy.jpg',
    PipeHype: 'https://s3-us-west-1.amazonaws.com/twitchchat/PipeHype.jpg',
    PixelBob: 'https://s3-us-west-1.amazonaws.com/twitchchat/PixelBob.jpg',
    PogChamp: 'https://s3-us-west-1.amazonaws.com/twitchchat/PogChamp.jpg',
    Poooound: 'https://s3-us-west-1.amazonaws.com/twitchchat/Poooound.jpg',
    PopCorn: 'https://s3-us-west-1.amazonaws.com/twitchchat/PopCorn.jpg',
    PowerUpL: 'https://s3-us-west-1.amazonaws.com/twitchchat/PowerUpL.jpg',
    PowerUpR: 'https://s3-us-west-1.amazonaws.com/twitchchat/PowerUpR.jpg',
    PraiseIt: 'https://s3-us-west-1.amazonaws.com/twitchchat/PraiseIt.jpg',
    PrimeMe: 'https://s3-us-west-1.amazonaws.com/twitchchat/PrimeMe.jpg',
    PunOko: 'https://s3-us-west-1.amazonaws.com/twitchchat/PunOko.jpg',
    PunchTrees: 'https://s3-us-west-1.amazonaws.com/twitchchat/PunchTrees.jpg',
    PurpleStar: 'https://s3-us-west-1.amazonaws.com/twitchchat/PurpleStar.jpg',
    RaccAttack: 'https://s3-us-west-1.amazonaws.com/twitchchat/RaccAttack.jpg',
    RalpherZ: 'https://s3-us-west-1.amazonaws.com/twitchchat/RalpherZ.jpg',
    RedCoat: 'https://s3-us-west-1.amazonaws.com/twitchchat/RedCoat.jpg',
    RedTeam: 'https://s3-us-west-1.amazonaws.com/twitchchat/RedTeam.jpg',
    ResidentSleeper:
      'https://s3-us-west-1.amazonaws.com/twitchchat/ResidentSleeper.jpg',
    RitzMitz: 'https://s3-us-west-1.amazonaws.com/twitchchat/RitzMitz.jpg',
    RlyTho: 'https://s3-us-west-1.amazonaws.com/twitchchat/RlyTho.jpg',
    RuleFive: 'https://s3-us-west-1.amazonaws.com/twitchchat/RuleFive.jpg',
    SMOrc: 'https://s3-us-west-1.amazonaws.com/twitchchat/SMOrc.jpg',
    SSSsss: 'https://s3-us-west-1.amazonaws.com/twitchchat/SSSsss.jpg',
    SabaPing: 'https://s3-us-west-1.amazonaws.com/twitchchat/SabaPing.jpg',
    SeemsGood: 'https://s3-us-west-1.amazonaws.com/twitchchat/SeemsGood.jpg',
    SeriousSloth:
      'https://s3-us-west-1.amazonaws.com/twitchchat/SeriousSloth.jpg',
    ShadyLulu: 'https://s3-us-west-1.amazonaws.com/twitchchat/ShadyLulu.jpg',
    ShazBotstix: 'https://s3-us-west-1.amazonaws.com/twitchchat/ShazBotstix.jpg',
    SmoocherZ: 'https://s3-us-west-1.amazonaws.com/twitchchat/SmoocherZ.jpg',
    SoBayed: 'https://s3-us-west-1.amazonaws.com/twitchchat/SoBayed.jpg',
    SoonerLater: 'https://s3-us-west-1.amazonaws.com/twitchchat/SoonerLater.jpg',
    Squid1: 'https://s3-us-west-1.amazonaws.com/twitchchat/Squid1.jpg',
    Squid2: 'https://s3-us-west-1.amazonaws.com/twitchchat/Squid2.jpg',
    Squid3: 'https://s3-us-west-1.amazonaws.com/twitchchat/Squid3.jpg',
    Squid4: 'https://s3-us-west-1.amazonaws.com/twitchchat/Squid4.jpg',
    StinkyCheese:
      'https://s3-us-west-1.amazonaws.com/twitchchat/StinkyCheese.jpg',
    StoneLightning:
      'https://s3-us-west-1.amazonaws.com/twitchchat/StoneLightning.jpg',
    StrawBeary: 'https://s3-us-west-1.amazonaws.com/twitchchat/StrawBeary.jpg',
    SuperVinlin: 'https://s3-us-west-1.amazonaws.com/twitchchat/SuperVinlin.jpg',
    SwiftRage: 'https://s3-us-west-1.amazonaws.com/twitchchat/SwiftRage.jpg',
    TBAngel: 'https://s3-us-west-1.amazonaws.com/twitchchat/TBAngel.jpg',
    TF2John: 'https://s3-us-west-1.amazonaws.com/twitchchat/TF2John.jpg',
    TPFufun: 'https://s3-us-west-1.amazonaws.com/twitchchat/TPFufun.jpg',
    TPcrunchyroll:
      'https://s3-us-west-1.amazonaws.com/twitchchat/TPcrunchyroll.jpg',
    TTours: 'https://s3-us-west-1.amazonaws.com/twitchchat/TTours.jpg',
    TakeNRG: 'https://s3-us-west-1.amazonaws.com/twitchchat/TakeNRG.jpg',
    TearGlove: 'https://s3-us-west-1.amazonaws.com/twitchchat/TearGlove.jpg',
    TehePelo: 'https://s3-us-west-1.amazonaws.com/twitchchat/TehePelo.jpg',
    ThankEgg: 'https://s3-us-west-1.amazonaws.com/twitchchat/ThankEgg.jpg',
    TheIlluminati:
      'https://s3-us-west-1.amazonaws.com/twitchchat/TheIlluminati.jpg',
    TheRinger: 'https://s3-us-west-1.amazonaws.com/twitchchat/TheRinger.jpg',
    TheTarFu: 'https://s3-us-west-1.amazonaws.com/twitchchat/TheTarFu.jpg',
    TheThing: 'https://s3-us-west-1.amazonaws.com/twitchchat/TheThing.jpg',
    ThunBeast: 'https://s3-us-west-1.amazonaws.com/twitchchat/ThunBeast.jpg',
    TinyFace: 'https://s3-us-west-1.amazonaws.com/twitchchat/TinyFace.jpg',
    TombRaid: 'https://s3-us-west-1.amazonaws.com/twitchchat/TombRaid.jpg',
    TooSpicy: 'https://s3-us-west-1.amazonaws.com/twitchchat/TooSpicy.jpg',
    TransgenderPride:
      'https://s3-us-west-1.amazonaws.com/twitchchat/TransgenderPride.jpg',
    TriHard: 'https://s3-us-west-1.amazonaws.com/twitchchat/TriHard.jpg',
    TwitchLit: 'https://s3-us-west-1.amazonaws.com/twitchchat/TwitchLit.jpg',
    TwitchRPG: 'https://s3-us-west-1.amazonaws.com/twitchchat/TwitchRPG.jpg',
    TwitchUnity: 'https://s3-us-west-1.amazonaws.com/twitchchat/TwitchUnity.jpg',
    TwitchVotes: 'https://s3-us-west-1.amazonaws.com/twitchchat/TwitchVotes.jpg',
    UWot: 'https://s3-us-west-1.amazonaws.com/twitchchat/UWot.jpg',
    UnSane: 'https://s3-us-west-1.amazonaws.com/twitchchat/UnSane.jpg',
    UncleNox: 'https://s3-us-west-1.amazonaws.com/twitchchat/UncleNox.jpg',
    VoHiYo: 'https://s3-us-west-1.amazonaws.com/twitchchat/VoHiYo.jpg',
    VoteNay: 'https://s3-us-west-1.amazonaws.com/twitchchat/VoteNay.jpg',
    VoteYea: 'https://s3-us-west-1.amazonaws.com/twitchchat/VoteYea.jpg',
    WTRuck: 'https://s3-us-west-1.amazonaws.com/twitchchat/WTRuck.jpg',
    WholeWheat: 'https://s3-us-west-1.amazonaws.com/twitchchat/WholeWheat.jpg',
    WutFace: 'https://s3-us-west-1.amazonaws.com/twitchchat/WutFace.jpg',
    YouDontSay: 'https://s3-us-west-1.amazonaws.com/twitchchat/YouDontSay.jpg',
    YouWHY: 'https://s3-us-west-1.amazonaws.com/twitchchat/YouWHY.jpg',
    bleedPurple: 'https://s3-us-west-1.amazonaws.com/twitchchat/bleedPurple.jpg',
    cmonBruh: 'https://s3-us-west-1.amazonaws.com/twitchchat/cmonBruh.jpg',
    copyThis: 'https://s3-us-west-1.amazonaws.com/twitchchat/copyThis.jpg',
    duDudu: 'https://s3-us-west-1.amazonaws.com/twitchchat/duDudu.jpg',
    imGlitch: 'https://s3-us-west-1.amazonaws.com/twitchchat/imGlitch.jpg',
    mcaT: 'https://s3-us-west-1.amazonaws.com/twitchchat/mcaT.jpg',
    panicBasket: 'https://s3-us-west-1.amazonaws.com/twitchchat/panicBasket.jpg',
    pastaThat: 'https://s3-us-west-1.amazonaws.com/twitchchat/pastaThat.jpg',
    riPepperonis:
      'https://s3-us-west-1.amazonaws.com/twitchchat/riPepperonis.jpg',
    twitchRaid: 'https://s3-us-west-1.amazonaws.com/twitchchat/twitchRaid.jpg'
  }
};
